# Generated by Django 3.2.4 on 2021-06-12 22:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidato', '0002_auto_20210611_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('resumo', models.CharField(default='', max_length=125)),
                ('descricao', models.CharField(default='', max_length=255)),
                ('tipo_contrato', models.CharField(choices=[('0', 'a combinar'), ('1', 'CLT'), ('2', 'PJ'), ('3', 'Temporário')], default='1', max_length=2)),
                ('remuneracao', models.CharField(default='a combinar', max_length=15)),
                ('beneficios', models.CharField(blank=True, default='', max_length=255)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Candidaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Aguardando contato'), ('AG', 'Entrevista agendada'), ('AF', 'Aguardando feedback'), ('PE', 'Processo encerrado')], default='AC', max_length=2)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga')),
            ],
        ),
    ]
