version: '3.7'
services:
    redis:
        image: redis:6-alpine
        ports:
            - "6379:6379"
        container_name: redis
        
    backend: 
        build:
            context: ./
            dockerfile: ./docker/Dockerfile

        env_file:
            - ./docker/.env
        volumes:
            - ./:/api
        ports:
            - 8000:8000
        container_name: api-vagas
        depends_on:
            - redis
    
   