version: '3.7'
services:
    backend: 
        build:
            context: ./
            dockerfile: ./docker/Dockerfile

        env_file:
            - ./docker/.env
        volumes:
            - ./:/api
        ports:
            - 8000:8000
        container_name: api-vagas
    
    redis:
        image: redis
        command: redis-server
        ports:
            - "6379:6379"
        container_name: redis